# //import platform
# import os

# # --- PATH HANDLING (Base) ---
# # Works on both Windows and Linux
# BASE_DIR = os.getcwd()
# LOG_FILE_PATH = os.path.join(BASE_DIR, "damage_reports.csv")

# # --- HARDWARE DETECTION, CAMERA & AI ENGINE ---
# # Detects Jetson Nano (aarch64) vs Laptop
# if platform.system() == "Linux" and platform.machine() == "aarch64":
#     # 1. Jetson CSI Camera Pipeline
#     INPUT_SOURCE = (
#         "nvarguscamerasrc ! video/x-raw(memory:NVMM), "
#         "width=(int)1280, height=(int)720, format=(string)NV12, framerate=(fraction)30/1 ! "
#         "nvvidconv flip-method=0 ! video/x-raw, format=(string)BGRx ! "
#         "videoconvert ! video/x-raw, format=(string)BGR ! appsink"
#     )
    
#     # 2. Jetson Optimized Model (TensorRT FP16)
#     # The code will look for the file generated by optimize.py
#     MODEL_PATH = os.path.join(BASE_DIR, "traffic_model_96.engine")
    
#     print("🚀 Running on Jetson Nano: Using CSI Camera & TensorRT Engine (.engine)")

# else:
#     # 1. Laptop Webcam
#     INPUT_SOURCE = 0 
    
#     # 2. Laptop Standard Model (PyTorch FP32)
#     MODEL_PATH = os.path.join(BASE_DIR, "traffic_model_96.pt")
    
#     print("💻 Running on Laptop: Using Webcam & Standard Model (.pt)")

# # --- THRESHOLDS ---
# CONFIDENCE_THRESHOLD = 0.40  # Only show signs we are 40%+ sure about

import platform
import os

BASE_DIR = os.getcwd()
LOG_FILE_PATH = os.path.join(BASE_DIR, "damage_reports.csv")

# --- SET THIS TO YOUR VIDEO FILE NAME ---
VIDEO_FILE = "traffic_video.mp4"  # <-- CHANGE THIS

if platform.system() == "Linux" and platform.machine() == "aarch64":
    # Jetson Nano
    INPUT_SOURCE = VIDEO_FILE
    MODEL_PATH = os.path.join(BASE_DIR, "traffic_model_96.engine")
    print("🚀 Running on Jetson Nano: Using video file & TensorRT")
else:
    # Laptop
    INPUT_SOURCE = VIDEO_FILE
    MODEL_PATH = os.path.join(BASE_DIR, "traffic_model_96.pt")
    print("💻 Running on Laptop: Using video file & PyTorch")

CONFIDENCE_THRESHOLD = 0.40